### ISSUE TITLE
make_ipsw iPhone3,1 iOS 4.3.3 not working

### ISSUE THREAD

**Issue by n30gurrrman** [dora2-iOS/s0meiyoshino#8]
If I make iOS 4.3.3 Custom ipsw, it shows some error and stopped working, the log is:

>**** s0meiyoshino v3.5.4 make_ipsw ****
iPhone3,1_7.1.2_11D257_Restore.ipsw OK
Please connect the target device to USB.
<enter>: 
getting shsh...
iPhone3,1_4.3.3_8J2_Restore.ipsw OK
Archive:  ../iPhone3,1_4.3.3_8J2_Restore.ipsw
  inflating: iBoot.n90ap.RELEASE.img3  
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: a9afd43f422e436b8c450de6e70e7e7b8be9ed27a743da796a207811da1e0b5cb2cf50ac36b7d1f56f0ee94effe33a9a
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: a9afd43f422e436b8c450de6e70e7e7b8be9ed27a743da796a207811da1e0b5cb2cf50ac36b7d1f56f0ee94effe33a9a
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: a9afd43f422e436b8c450de6e70e7e7b8be9ed27a743da796a207811da1e0b5cb2cf50ac36b7d1f56f0ee94effe33a9a
Archive:  ../iPhone3,1_4.3.3_8J2_Restore.ipsw
  inflating: LLB.n90ap.RELEASE.img3  
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 6167799a88c1431bd95de7abad6492efb6d4ebdc56b28c7e31f4d06da689975dc65aeb70ee6e15d4b92c61498536a9f6
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 6167799a88c1431bd95de7abad6492efb6d4ebdc56b28c7e31f4d06da689975dc65aeb70ee6e15d4b92c61498536a9f6
/tmp/xpwn/ipsw-patch/img3.c:createAbstractFileFromImg3:643: 6167799a88c1431bd95de7abad6492efb6d4ebdc56b28c7e31f4d06da689975dc65aeb70ee6e15d4b92c61498536a9f6
a iBoot
Hashing IPSW...
Matching IPSW in FirmwareBundles/... (b2e22154...)
checking: FirmwareBundles//Down_iPhone3,1_4.3.3_8J2.bundle/Info.plist
loading: 038-1423-003.dmg (630390784)
loading: 038-1437-003.dmg (24873156)
loading: 038-1449-003.dmg (23840964)
loading: BuildManifest.plist (22691)
loading: Firmware/ (0)
loading: Firmware/all_flash/ (0)
loading: Firmware/all_flash/all_flash.n90ap.production/ (0)
loading: Firmware/all_flash/all_flash.n90ap.production/applelogo-640x960.s5l8930x.img3 (15172)
loading: Firmware/all_flash/all_flash.n90ap.production/batterycharging0-640x960.s5l8930x.img3 (11844)
loading: Firmware/all_flash/all_flash.n90ap.production/batterycharging1-640x960.s5l8930x.img3 (37124)
loading: Firmware/all_flash/all_flash.n90ap.production/batteryfull-640x960.s5l8930x.img3 (655300)
loading: Firmware/all_flash/all_flash.n90ap.production/batterylow0-640x960.s5l8930x.img3 (170692)
loading: Firmware/all_flash/all_flash.n90ap.production/batterylow1-640x960.s5l8930x.img3 (40004)
loading: Firmware/all_flash/all_flash.n90ap.production/DeviceTree.n90ap.img3 (60612)
loading: Firmware/all_flash/all_flash.n90ap.production/glyphcharging-640x960.s5l8930x.img3 (7364)
loading: Firmware/all_flash/all_flash.n90ap.production/glyphplugin-640x960.s5l8930x.img3 (7044)
loading: Firmware/all_flash/all_flash.n90ap.production/iBoot.n90ap.RELEASE.img3 (223620)
loading: Firmware/all_flash/all_flash.n90ap.production/LLB.n90ap.RELEASE.img3 (100740)
loading: Firmware/all_flash/all_flash.n90ap.production/manifest (387)
loading: Firmware/all_flash/all_flash.n90ap.production/recoverymode-640x960.s5l8930x.img3 (129604)
... 
run 3255: start=871890944 sectors=512, length=262144, fileOffset=0x254d8d26
run 3256: start=872153088 sectors=512, length=262144, fileOffset=0x25518d26
run 3257: start=872415232 sectors=512, length=238820, fileOffset=0x25558d26
run 3258: start=872677376 sectors=512, length=262144, fileOffset=0x2559320a
run 3259: start=872939520 sectors=512, length=262144, fileOffset=0x255d320a
run 3260: start=873201664 sectors=512, length=262144, fileOffset=0x2561320a
run 3261: start=873463808 sectors=512, length=262144, fileOffset=0x2565320a
run 3262: start=873725952 sectors=512, length=262144, fileOffset=0x2569320a
run 3263: start=873988096 sectors=512, length=224169, fileOffset=0x256d320a
run 3264: start=874250240 sectors=512, length=149163, fileOffset=0x25709db3
run 3265: start=874512384 sectors=512, length=26600, fileOffset=0x2572e45e
run 3266: start=874774528 sectors=512, length=13453, fileOffset=0x25734c46
run 3267: start=875036672 sectors=512, length=17069, fileOffset=0x257380d3
run 3268: start=875298816 sectors=512, length=13373, fileOffset=0x2573c380
run 3269: start=875560960 sectors=512, length=9817, fileOffset=0x2573f7bd
run 3270: start=875823104 sectors=512, length=37147, fileOffset=0x25741e16
run 3271: start=876085248 sectors=512, length=224791, fileOffset=0x2574af31
run 3272: start=876347392 sectors=512, length=141390, fileOffset=0x25781d48
run 3273: start=876609536 sectors=512, length=170641, fileOffset=0x257a4596
run 3274: start=876871680 sectors=512, length=60852, fileOffset=0x257ce027
run 3275: start=877133824 sectors=512, length=185984, fileOffset=0x257dcddb
run 3276: start=877395968 sectors=512, length=212290, fileOffset=0x2580a45b
run 3277: start=877658112 sectors=512, length=153616, fileOffset=0x2583e19d
run 3278: start=877920256 sectors=512, length=101566, fileOffset=0x258639ad
run 3279: start=878182400 sectors=512, length=211885, fileOffset=0x2587c66b
run 3280: start=878444544 sectors=512, length=127451, fileOffset=0x258b0218
run 3281: start=878706688 sectors=512, length=58100, fileOffset=0x258cf3f3
run 3282: start=878968832 sectors=16, length=7662, fileOffset=0x258dd6e7
run 3284: start=878988288 sectors=1, length=148, fileOffset=0x258df4d5
Growing root to minimum: 950
unencrypted ramdisk
growing ramdisk: 23838720 -> 23838720
Cannot shrink volume
patching usr/sbin/asr (FirmwareBundles//Down_iPhone3,1_4.3.3_8J2.bundle/asr.patch)... retrieving...patching...writing... success
start create restore options
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CreateFilesystemPartitions</key>
<true/>
<key>SystemPartitionSize</key>
<integer>950</integer>
<key>UpdateBaseband</key>
<false/>
</dict>
</plist>
error: /tmp/xpwn/hfs/rawfile.c:233: allocate
error: Undefined error: 0
[ERROR] failed make ipsw

**Comment by dora2-iOS** [comment]
iOS 4.3.3 has been discontinued. Please use iOS 4.3.5.
